### ISSUE TITLE
Passwords are sometimes the wrong length

### ISSUE THREAD

**Issue by alexandervandekleutab** [brendanashworth/generate-password#76] opened 2022-06-29 20:18 UTC
The following will sometimes generate passwords of length 7 containing no special characters:

```typescript
passwordGenerator.generate({
      length: 8,
      strict: true,
      numbers: true,
      lowercase: true,
      uppercase: true,
      symbols: true,
      // These exclusions are either reserved(before space)
      // or unsafe(including and after space) characters for URLs
      exclude: '&$+,/:;=?@# <>[]{}|^%',
    })
```

We are passing this password to a callback that generates emails by directly injecting the password into a URL. Therefore we cannot pass symbols usually reserved for URLs. This code generated the password `ADd9xFM` which is 7 characters long.

**Comment by brendanashworth** [comment] 2022-06-30 17:33
@alexandervandekleutab not convinced this is an issue on our end. I can't seem to reproduce even with a lot of passwords:
```javascript
> gen.generateMultiple(1000000, options).filter(s => s.length != 8)
[]
```
After stripping out the characters you exclude, `encodeURI` still gives different characters. Do you want to exclude those too?
```javascript
> let symbols = '!@#$%^&*()+_-=}{[]|:;"/?.><,`~'
undefined
> let passthru = symbols.split('').filter(c => '&$+,/:;=?@# <>[]{}|^%'.indexOf(c) === -1)
undefined
> passthru
[
  '!', '*', '(', ')',
  '_', '-', '"', '.',
  '`', '~'
]
> passthru.map(c => encodeURI(c))
[
  '!',   '*', '(',
  ')',   '_', '-',
  '%22', '.', '%60',
  '~'
]
```

**Comment by brendanashworth** [comment] 2022-09-17 23:35
Going to close this because it hasn't been reproduced.

**Closed by brendanashworth** 2022-09-17 23:35 UTC
